#!/usr/bin/env python3
"""Generate the single-file llmwatch.py from the llmwatch/ package.

The package is the source you edit. The file at the repository root is built
from it, and is what

    curl -O .../llmwatch.py && ./llmwatch.py

downloads: one script, standard library only, no install step. That promise is
older than the package layout and is not worth giving up, so it is kept by
generating the file rather than by writing everything in it.

The module order is worked out from the imports themselves rather than written
down here, so it cannot drift. That also makes this script the thing that
enforces the layering: a cycle between two modules has no valid order, and the
build stops instead of emitting a file that fails at import time.

    python tools/bundle.py            rewrite llmwatch.py
    python tools/bundle.py --check    fail if it is out of date (used by CI)
"""

import argparse
import ast
import os
import stat
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACKAGE = os.path.join(ROOT, "llmwatch")
TARGET = os.path.join(ROOT, "llmwatch.py")

GENERATED_NOTE = """
This file is generated by tools/bundle.py from the llmwatch/ package.
Edit the package, not this file, and run:

    python tools/bundle.py

The two are checked against each other in CI, so an edit made here alone will
fail the build rather than quietly disappear at the next release.
"""

# Emitted verbatim at the top, because both are conditional and neither survives
# being reduced to a plain `import`.
OPTIONAL_IMPORTS = '''
try:                       # POSIX only; the TUI degrades to no-keyboard elsewhere
    import termios
    import tty
except ImportError:        # pragma: no cover - Windows
    termios = None
    tty = None

try:
    import queue
except ImportError:  # pragma: no cover - py2 only, never hit
    queue = None
'''

MAIN_GUARD = '''

if __name__ == "__main__":
    sys.exit(main())
'''


def module_files():
    """Every real module in the package, in no particular order yet."""
    skip = {"__init__.py", "__main__.py"}
    return sorted(name[:-3] for name in os.listdir(PACKAGE)
                  if name.endswith(".py") and name not in skip)


def read(name):
    with open(os.path.join(PACKAGE, name + ".py")) as fh:
        return fh.read()


def local_imports(tree):
    """The names of sibling modules this one imports from."""
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.level == 1 and node.module:
            found.add(node.module)
    return found


def order_modules(sources):
    """Topological order: every module after the ones it imports from.

    Ties are broken alphabetically so the output is byte-stable across runs and
    machines; a rebuild that reordered the file would make every diff useless.
    """
    deps = {name: local_imports(ast.parse(src)) & set(sources)
            for name, src in sources.items()}
    ordered, placed = [], set()
    remaining = sorted(deps)
    while remaining:
        ready = [n for n in remaining if deps[n] <= placed]
        if not ready:
            stuck = ", ".join(sorted(remaining))
            raise SystemExit(
                "tools/bundle.py: import cycle between: %s\n"
                "There is no order in which these can be concatenated. Break "
                "the cycle by moving the shared definitions down a layer."
                % stuck)
        for name in ready:
            ordered.append(name)
            placed.add(name)
            remaining.remove(name)
    return ordered


def strip(src, name):
    """One module's body: no docstring, no imports, everything else verbatim.

    The docstring is kept, as a comment, so the reasoning in it survives into
    the single-file build too.
    """
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)

    drop = set()
    doc = ast.get_docstring(tree)
    for node in tree.body:
        is_doc = (isinstance(node, ast.Expr)
                  and isinstance(node.value, ast.Constant)
                  and isinstance(node.value.value, str)
                  and node is tree.body[0])
        is_import = isinstance(node, (ast.Import, ast.ImportFrom))
        is_optional = (isinstance(node, ast.Try)
                       and any(isinstance(n, (ast.Import, ast.ImportFrom))
                               for n in ast.walk(node)))
        if is_doc or is_import or is_optional:
            drop.update(range(node.lineno - 1, node.end_lineno))

    body = "".join(line for i, line in enumerate(lines) if i not in drop)

    banner = ["# " + "-" * 74 + "\n", "# %s\n" % name, "#\n"]
    for line in (doc or "").strip().splitlines():
        banner.append(("# " + line).rstrip() + "\n")
    banner.append("# " + "-" * 74 + "\n")
    return "".join(banner) + "\n" + body.strip("\n") + "\n"


def stdlib_imports(sources):
    """The union of every plain `import x` across the package, deduplicated."""
    names = set()
    for src in sources.values():
        for node in ast.parse(src).body:
            if isinstance(node, ast.Import):
                for alias in node.names:
                    names.add(alias.name)
            elif isinstance(node, ast.ImportFrom) and node.level == 0:
                names.add("from %s import %s"
                          % (node.module,
                             ", ".join(a.name for a in node.names)))
    plain = sorted(n for n in names if not n.startswith("from "))
    froms = sorted(n for n in names if n.startswith("from "))
    return ("".join("import %s\n" % n for n in plain)
            + "".join(n + "\n" for n in froms))


def build():
    names = module_files()
    sources = {name: read(name) for name in names}
    ordered = order_modules(sources)

    init = ast.parse(open(os.path.join(PACKAGE, "__init__.py")).read())
    doc = ast.get_docstring(init) or ""

    out = ["#!/usr/bin/env python3\n",
           '"""%s\n%s"""\n\n' % (doc.rstrip(), GENERATED_NOTE)]
    out.append(stdlib_imports(sources))
    out.append(OPTIONAL_IMPORTS)
    out.append("\n")
    for name in ordered:
        out.append("\n" + strip(sources[name], name) + "\n")
    out.append(MAIN_GUARD)

    text = "".join(out)
    # Cheap self-check: the result has to parse, and has to still be the flat
    # namespace the single-file version always was.
    tree = ast.parse(text)
    seen, dupes = set(), []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            got = [node.name]
        elif isinstance(node, ast.Assign):
            got = [t.id for t in node.targets if isinstance(t, ast.Name)]
        else:
            got = []
        for n in got:
            if n in seen:
                dupes.append(n)
            seen.add(n)
    if dupes:
        raise SystemExit("tools/bundle.py: duplicate top-level names: %s"
                         % ", ".join(sorted(set(dupes))))
    return text


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if llmwatch.py is out of date")
    args = parser.parse_args(argv)

    text = build()
    current = open(TARGET).read() if os.path.exists(TARGET) else None

    if args.check:
        if current != text:
            sys.stderr.write(
                "llmwatch.py is out of date with the llmwatch/ package.\n"
                "Run: python tools/bundle.py\n")
            return 1
        print("llmwatch.py is up to date (%d lines)" % len(text.splitlines()))
        return 0

    if current == text:
        print("llmwatch.py already up to date")
        return 0
    # The generated file needs its executable bit: it carries a shebang, and the
    # documented install is `curl -O ... && ./llmwatch.py`. Regenerating it must
    # not drop that.
    #
    # Adding the owner bit to whatever mode is already there, rather than
    # writing a fixed 0o755, is both narrower and more correct. git records
    # executability from exactly that one bit, so it is all that is needed, and
    # a rebuild then cannot widen the permissions of a file somebody chose to
    # restrict. Rewriting through an existing path keeps the old mode, so this
    # only does real work the first time the file is created.
    mode = os.stat(TARGET).st_mode if os.path.exists(TARGET) else None
    with open(TARGET, "w") as fh:
        fh.write(text)
    if mode is None:
        mode = os.stat(TARGET).st_mode
    os.chmod(TARGET, mode | stat.S_IXUSR)
    print("wrote llmwatch.py (%d lines, %d modules)"
          % (len(text.splitlines()), len(module_files())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
